"""Flask application factory for the fintech demo app's REST API.

Milestone 1 scope: mock account/transaction data model, a rule-based
categorization engine, and a seeded synthetic data generator standing
in for a real bank feed. Consistent with the rest of this repo's arcs:
SQLite via stdlib sqlite3, bcrypt + HS256 JWT auth, Flask for routing.

SAFETY NOTE: this app never connects to a real bank, payment
processor, or brokerage. All account/transaction data is either
entered manually through the API or generated by mock_data.py's
seeded synthetic generator. See README.md.
"""
from __future__ import annotations

from flask import Flask, jsonify

from . import db as db_module


def create_app(db_path: str = ":memory:", jwt_secret: str = "dev-secret-change-me") -> Flask:
    app = Flask(__name__)
    conn = db_module.connect(db_path)
    db_module.init_db(conn)

    app.config["DB_CONN"] = conn
    app.config["DB_PATH"] = db_path
    app.config["JWT_SECRET"] = jwt_secret

    from .routes import account_routes, auth_routes, demo_routes, transaction_routes

    app.register_blueprint(auth_routes.bp)
    app.register_blueprint(account_routes.bp)
    app.register_blueprint(transaction_routes.bp)
    app.register_blueprint(demo_routes.bp)

    @app.get("/api/health")
    def health():
        return jsonify(status="ok")

    return app
