"""SQLite schema + data-access helpers for the fintech demo app.

Dependency-free (stdlib sqlite3), following the same pattern as the
other arcs in this repo (dev_collab_platform, saas_starter,
lms_platform): thin functions taking a connection and plain arguments,
returning sqlite3.Row objects that route handlers convert to dicts
with row_to_dict(). One process-wide connection is opened by the app
factory; multi-statement writes go through the transaction() context
manager so they either all land or all roll back.

IMPORTANT: this app never talks to a real bank. Every account and
transaction row in this database is either entered by hand through the
API or generated by mock_data.py's seeded synthetic generator. See
README.md.
"""
from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from pathlib import Path

SCHEMA = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    account_type TEXT NOT NULL CHECK (account_type IN ('checking', 'savings', 'credit_card')),
    institution_name TEXT NOT NULL DEFAULT 'Demo Bank',
    currency TEXT NOT NULL DEFAULT 'USD',
    is_mock INTEGER NOT NULL DEFAULT 0 CHECK (is_mock IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    -- amount sign convention: positive = money IN to the account (income,
    -- deposit, refund), negative = money OUT (purchase, fee, transfer out).
    amount REAL NOT NULL,
    merchant TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'uncategorized',
    -- set once a human (not the categorization engine) has chosen the
    -- category, so re-running auto-categorization never clobbers it.
    category_is_manual INTEGER NOT NULL DEFAULT 0 CHECK (category_is_manual IN (0, 1)),
    posted_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_transactions_account ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_posted_at ON transactions(posted_at);
CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts(user_id);
"""


def connect(db_path: str) -> sqlite3.Connection:
    if db_path != ":memory:":
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db(conn: sqlite3.Connection) -> None:
    conn.executescript(SCHEMA)
    conn.commit()


@contextmanager
def transaction(conn: sqlite3.Connection):
    """Wrap a block of writes in a single commit/rollback."""
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise


def row_to_dict(row: sqlite3.Row | None) -> dict | None:
    if row is None:
        return None
    return dict(row)


# -- users --------------------------------------------------------------

def create_user(conn, email: str, password_hash: str) -> int:
    cur = conn.execute(
        "INSERT INTO users (email, password_hash) VALUES (?, ?)",
        (email, password_hash),
    )
    return cur.lastrowid


def get_user_by_email(conn, email: str):
    return conn.execute("SELECT * FROM users WHERE email = ?", (email,)).fetchone()


def get_user_by_id(conn, user_id: int):
    return conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()


# -- accounts -------------------------------------------------------------

def create_account(conn, user_id: int, name: str, account_type: str,
                    institution_name: str = "Demo Bank", currency: str = "USD",
                    is_mock: bool = False) -> int:
    cur = conn.execute(
        "INSERT INTO accounts (user_id, name, account_type, institution_name, currency, is_mock) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (user_id, name, account_type, institution_name, currency, int(is_mock)),
    )
    return cur.lastrowid


def get_account(conn, account_id: int):
    return conn.execute("SELECT * FROM accounts WHERE id = ?", (account_id,)).fetchone()


def list_accounts_for_user(conn, user_id: int):
    return conn.execute(
        "SELECT * FROM accounts WHERE user_id = ? ORDER BY id", (user_id,)
    ).fetchall()


def delete_account(conn, account_id: int) -> None:
    conn.execute("DELETE FROM accounts WHERE id = ?", (account_id,))


def account_balance(conn, account_id: int) -> float:
    """Sum of all transaction amounts on the account. There is no separate
    stored balance column -- it is always derived from transactions, so it
    can never drift out of sync with them."""
    row = conn.execute(
        "SELECT COALESCE(SUM(amount), 0) AS total FROM transactions WHERE account_id = ?",
        (account_id,),
    ).fetchone()
    return round(row["total"], 2)


# -- transactions -----------------------------------------------------------

def create_transaction(conn, account_id: int, amount: float, merchant: str,
                        description: str, category: str, posted_at: str,
                        category_is_manual: bool = False) -> int:
    cur = conn.execute(
        "INSERT INTO transactions "
        "(account_id, amount, merchant, description, category, category_is_manual, posted_at) "
        "VALUES (?, ?, ?, ?, ?, ?, ?)",
        (account_id, amount, merchant, description, category, int(category_is_manual), posted_at),
    )
    return cur.lastrowid


def get_transaction(conn, transaction_id: int):
    return conn.execute(
        "SELECT * FROM transactions WHERE id = ?", (transaction_id,)
    ).fetchone()


def list_transactions_for_account(conn, account_id: int, category: str | None = None,
                                   start_date: str | None = None, end_date: str | None = None):
    query = "SELECT * FROM transactions WHERE account_id = ?"
    params: list = [account_id]
    if category:
        query += " AND category = ?"
        params.append(category)
    if start_date:
        query += " AND posted_at >= ?"
        params.append(start_date)
    if end_date:
        query += " AND posted_at <= ?"
        params.append(end_date)
    query += " ORDER BY posted_at DESC, id DESC"
    return conn.execute(query, params).fetchall()


def list_transactions_for_user(conn, user_id: int, category: str | None = None,
                                start_date: str | None = None, end_date: str | None = None):
    query = (
        "SELECT t.* FROM transactions t "
        "JOIN accounts a ON a.id = t.account_id "
        "WHERE a.user_id = ?"
    )
    params: list = [user_id]
    if category:
        query += " AND t.category = ?"
        params.append(category)
    if start_date:
        query += " AND t.posted_at >= ?"
        params.append(start_date)
    if end_date:
        query += " AND t.posted_at <= ?"
        params.append(end_date)
    query += " ORDER BY t.posted_at DESC, t.id DESC"
    return conn.execute(query, params).fetchall()


def update_transaction_category(conn, transaction_id: int, category: str,
                                 category_is_manual: bool = True) -> None:
    conn.execute(
        "UPDATE transactions SET category = ?, category_is_manual = ? WHERE id = ?",
        (category, int(category_is_manual), transaction_id),
    )


def delete_transaction(conn, transaction_id: int) -> None:
    conn.execute("DELETE FROM transactions WHERE id = ?", (transaction_id,))


def list_uncategorized_or_auto_transactions(conn, user_id: int):
    """Transactions belonging to user_id whose category was never manually
    set -- the safe set to re-run the categorization engine over."""
    query = (
        "SELECT t.* FROM transactions t "
        "JOIN accounts a ON a.id = t.account_id "
        "WHERE a.user_id = ? AND t.category_is_manual = 0"
    )
    return conn.execute(query, (user_id,)).fetchall()
